const localProducts = [
  {
    _id: "p1",
    id: "p1",
    name: "ADIDAS YEEZY BOOST 350 V2 PHANTOM",
    brand: "Yeezy",
    price: 18500,
    images: ["https://images.unsplash.com/photo-1586525198428-225f6f12cff5?auto=format&fit=crop&w=1000&q=80"],
    sizes: [7, 8, 9, 10, 11],
    rating: 4.8,
    category: "Sneakers",
    targetGender: "Men",
    description: "The peak of comfort and hype. Original quality Yeezy Boost 350 V2 with responsive Primeknit upper."
  },
  {
    _id: "p2",
    id: "p2",
    name: "JORDAN 1 RETRO HIGH CHICAGO",
    brand: "Jordan",
    price: 24999,
    images: ["https://images.unsplash.com/photo-1616124619460-ff4ed8f4683c?auto=format&fit=crop&w=1000&q=80"],
    sizes: [7, 8, 9, 10],
    rating: 4.9,
    category: "Sneakers",
    targetGender: "Men",
    description: "The most iconic sneaker in history. Red, White, and Black perfection with encapsulated Air-Sole cushioning."
  },
  {
    _id: "p3",
    id: "p3",
    name: "NIKE AIR MAX 270 VOLT",
    brand: "Nike",
    price: 12450,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=80"],
    sizes: [6, 7, 8, 9, 10],
    rating: 4.7,
    category: "Sneakers",
    targetGender: "Men",
    description: "Maximum air, maximum comfort. The perfect lifestyle sneaker engineered with 270-degree Max Air unit."
  },
  {
    _id: "p4",
    id: "p4",
    name: "PUMA RS-X REINVENT WOMEN",
    brand: "Puma",
    price: 9800,
    images: ["https://images.unsplash.com/photo-1584735175315-9d5df23860e6?auto=format&fit=crop&w=1000&q=80"],
    sizes: [5, 6, 7, 8],
    rating: 4.6,
    category: "Women",
    targetGender: "Women",
    description: "Bulky silhouette meets pastel elegance. Designed for high fashion and all-day ergonomic support."
  },
  {
    _id: "p5",
    id: "p5",
    name: "ADIDAS ULTRABOOST 5.0 LUXE",
    brand: "Adidas",
    price: 15999,
    images: ["https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=1000&q=80"],
    sizes: [6, 7, 8, 9, 10],
    rating: 4.8,
    category: "Women",
    targetGender: "Women",
    description: "The ultimate running shoe with energy-returning Boost technology and tailored female ergonomics."
  },
  {
    _id: "p6",
    id: "p6",
    name: "JORDAN 4 RETRO BLACK CAT",
    brand: "Jordan",
    price: 28500,
    images: ["https://images.unsplash.com/photo-1597045566774-ed40434a4a54?auto=format&fit=crop&w=1000&q=80"],
    sizes: [8, 9, 10, 11],
    rating: 4.9,
    category: "Sneakers",
    targetGender: "Men",
    description: "All-black everything. The stealthiest Jordan ever made, draped in plush nubuck and matte accents."
  },
  {
    _id: "v1",
    id: "v1",
    name: "AERO CRAFT ALPHA",
    brand: "Samadhan",
    price: 4999,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80", "/Shoes.png"],
    sizes: [7, 8, 9, 10],
    rating: 4.9,
    category: "Men",
    targetGender: "Men",
    description: "Precision-engineered lifestyle silhouette handcrafted from full-grain Tuscan calfskin in Nashik."
  },
  {
    _id: "v2",
    id: "v2",
    name: "MONARCH LUXE DERBY",
    brand: "Samadhan",
    price: 5499,
    images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80"],
    sizes: [7, 8, 9, 10, 11],
    rating: 4.9,
    category: "Formal",
    targetGender: "Men",
    description: "Timeless tailored formal derby shoe. Goodyear-welted with hand-burnished carnauba wax patina."
  },
  {
    _id: "v3",
    id: "v3",
    name: "NEO KINETIC SPRINT",
    brand: "Samadhan",
    price: 3899,
    images: ["https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80"],
    sizes: [6, 7, 8, 9, 10],
    rating: 4.7,
    category: "Women",
    targetGender: "Women",
    description: "Aerodynamic responsiveness and featherweight foam core engineered for high-mileage comfort."
  },
  {
    _id: "v4",
    id: "v4",
    name: "JUNIOR COURIER RETRO",
    brand: "Samadhan Kids",
    price: 2499,
    images: ["https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80"],
    sizes: [1, 2, 3, 4, 5],
    rating: 4.9,
    category: "Kids",
    targetGender: "Kids",
    description: "Ergonomically contoured for growing feet. Soft-flex natural rubber outsoles and anti-microbial lining."
  },
  {
    _id: "w1",
    id: "w1",
    name: "MILAN SUEDE STILETTO HEEL",
    brand: "Samadhan Atelier",
    price: 6499,
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1000&q=80"],
    sizes: [5, 6, 7, 8],
    rating: 4.9,
    category: "Women",
    targetGender: "Women",
    description: "Handcrafted Italian velvet suede stiletto with shock-absorbing forefoot padding and rose gold buckle."
  },
  {
    _id: "w2",
    id: "w2",
    name: "PARISIAN QUILTED BALLET FLAT",
    brand: "Samadhan Atelier",
    price: 3999,
    images: ["https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=1000&q=80"],
    sizes: [5, 6, 7, 8, 9],
    rating: 4.8,
    category: "Women",
    targetGender: "Women",
    description: "Ultra-supple lambskin leather flats with delicate grosgrain bow and hand-stitched memory foam insole."
  },
  {
    _id: "w3",
    id: "w3",
    name: "VERONA CHELSEA ANKLE BOOT",
    brand: "Samadhan Atelier",
    price: 6899,
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1000&q=80"],
    sizes: [5, 6, 7, 8],
    rating: 4.9,
    category: "Women",
    targetGender: "Women",
    description: "Goodyear welted women's Chelsea boot made from vegetable-tanned full-grain leather with contoured arch."
  },
  {
    _id: "k1",
    id: "k1",
    name: "NIKE AIR FORCE 1 LV8 JUNIOR",
    brand: "Nike Kids",
    price: 5499,
    images: ["https://images.unsplash.com/photo-1507464098880-e367bc5d2c08?auto=format&fit=crop&w=1000&q=80"],
    sizes: [2, 3, 4, 5, 6],
    rating: 4.9,
    category: "Kids",
    targetGender: "Kids",
    description: "The timeless basketball icon scaled for younger icons. Durable real leather with classic pivot-circle traction."
  },
  {
    _id: "k2",
    id: "k2",
    name: "ADIDAS SUPERSTAR ELASTIC KIDS",
    brand: "Adidas Kids",
    price: 3899,
    images: ["https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=1000&q=80"],
    sizes: [1, 2, 3, 4, 5],
    rating: 4.8,
    category: "Kids",
    targetGender: "Kids",
    description: "Iconic rubber shell toe with easy hook-and-loop straps. OrthoLite sockliner keeps small feet fresh all day."
  },
  {
    _id: "k3",
    id: "k3",
    name: "NASHIK ACADEMY SCHOOL DERBY",
    brand: "Samadhan Junior",
    price: 2199,
    images: ["https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80"],
    sizes: [1, 2, 3, 4, 5, 6],
    rating: 4.9,
    category: "Kids",
    targetGender: "Kids",
    description: "Indestructible school shoe crafted from thick full-grain bovine leather with scuff-resistant toe reinforcement."
  }
];

export default localProducts;
