const localProducts = [
  {
    _id: "p1",
    id: "p1",
    name: "SAMADHAN PREMIUM SNEAKER ALPHA",
    brand: "New Samadhan Shoes Mart",
    price: 3499,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0006.jpg", "/New-Samadhan-Shoe-Mart/IMG-20260928-WA0007.jpg"],
    sizes: [6, 7, 8, 9, 10],
    rating: 4.9,
    category: "Sneakers",
    targetGender: "Men",
    description: "Original premium quality sneaker engineered for high comfort and streetstyle legacy. Handcrafted upper with cushioned responsive core."
  },
  {
    _id: "p2",
    id: "p2",
    name: "CLASSIC MEN FORMAL OXFORD",
    brand: "New Samadhan Shoes Mart",
    price: 4200,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0008.jpg", "/New-Samadhan-Shoe-Mart/IMG-20260928-WA0009.jpg"],
    sizes: [7, 8, 9, 10],
    rating: 4.8,
    category: "Formal",
    targetGender: "Men",
    description: "Elegant and timeless tailored formal shoe with hand-burnished finish. Perfect for weddings, corporate, and formal ceremonies."
  },
  {
    _id: "p3",
    id: "p3",
    name: "COMFORT FLEX DAILY SANDALS",
    brand: "New Samadhan Shoes Mart",
    price: 1899,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0010.jpg"],
    sizes: [6, 7, 8, 9, 10],
    rating: 4.7,
    category: "Men",
    targetGender: "Men",
    description: "Heavy-duty everyday sandals featuring superior arch support, leather straps, and non-slip rubber grip."
  },
  {
    _id: "p4",
    id: "p4",
    name: "WOMEN ELEGANT LUXE CHAPPAL",
    brand: "New Samadhan Shoes Mart",
    price: 1599,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0011.jpg", "/New-Samadhan-Shoe-Mart/IMG-20260928-WA0012.jpg"],
    sizes: [5, 6, 7, 8],
    rating: 4.9,
    category: "Women",
    targetGender: "Women",
    description: "Beautiful handcrafted ladies sandals with traditional styling and soft cushion footbed for ultimate comfort."
  },
  {
    _id: "p5",
    id: "p5",
    name: "LADIES COMFORT WALK SANDALS",
    brand: "New Samadhan Shoes Mart",
    price: 1999,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0013.jpg"],
    sizes: [5, 6, 7, 8],
    rating: 4.8,
    category: "Women",
    targetGender: "Women",
    description: "Ergonomically engineered for working women. Modern silhouette meets rich finish and multi-layered cushioning."
  },
  {
    _id: "p6",
    id: "p6",
    name: "SNEAKERS URBAN PRO MAX",
    brand: "New Samadhan Shoes Mart",
    price: 2999,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0014.jpg"],
    sizes: [7, 8, 9, 10],
    rating: 4.8,
    category: "Sneakers",
    targetGender: "Men",
    description: "Premium casual sneakers designed for maximum flexibility, breathability, and durability in daily wear."
  },
  {
    _id: "v1",
    id: "v1",
    name: "JUNIOR COMFORT RUNNER KIDS",
    brand: "Samadhan Kids",
    price: 1299,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0015.jpg"],
    sizes: [1, 2, 3, 4, 5],
    rating: 4.9,
    category: "Kids",
    targetGender: "Kids",
    description: "Perfect lightweight support for growing feet. Equipped with anti-bacterial inner lining and high flex soles."
  },
  {
    _id: "v2",
    id: "v2",
    name: "BOYS ADVENTURE SPORT SHOES",
    brand: "Samadhan Kids",
    price: 1499,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0016.jpg"],
    sizes: [2, 3, 4, 5, 6],
    rating: 4.7,
    category: "Kids",
    targetGender: "Kids",
    description: "Scuff-resistant reinforced toes with premium fit. Built for heavy playground use and school sports actions."
  },
  {
    _id: "v3",
    id: "v3",
    name: "MEN ECO-FLEX COMFORT LOAFERS",
    brand: "New Samadhan Shoes Mart",
    price: 2499,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0017.jpg"],
    sizes: [6, 7, 8, 9, 10],
    rating: 4.9,
    category: "Formal",
    targetGender: "Men",
    description: "Easy slip-on loafers handcrafted with premium stitching. Combines corporate smartness with outdoor freedom."
  },
  {
    _id: "v4",
    id: "v4",
    name: "PREMIUM LEATHER SANDALS DELUXE",
    brand: "New Samadhan Shoes Mart",
    price: 2199,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0018.jpg"],
    sizes: [7, 8, 9, 10, 11],
    rating: 4.8,
    category: "Men",
    targetGender: "Men",
    description: "Traditional pure comfort sandals. Features double lockstitched sole joins and customized contour mapping."
  },
  {
    _id: "art1401",
    id: "art1401",
    name: "ART 1401 GOAT LEATHER TPR SOLE",
    brand: "Mochi Brand Style",
    price: 3299,
    images: ["/New-Samadhan-Shoe-Mart/IMG-20260928-WA0032.jpg"],
    sizes: [6, 7, 8, 9, 10],
    rating: 5.0,
    category: "Formal",
    targetGender: "Men",
    description: "High-quality Mochi brand style premium shoe crafted from genuine goat leather with a durable and flexible TPR sole for premium all-day elite comfort."
  }
];

export default localProducts;
